# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger: none

pr:
- master

pool:
  vmImage: 'vs2017-win2016'

steps:
- task: Npm@1
  inputs:
    command: 'install'

- task: Grunt@0
  inputs:
    gruntFile: '$(Build.Repository.LocalPath)/gruntfile.js'
    targets: 'build'

- task: AzureFileCopy@3
  inputs:
    sourcePath: '$(Build.Repository.LocalPath)/dist'
    azureSubscription: conn
    destination: azureBlob
    storage: outdoorenterprisesinccom
    containerName: "dev"

- task: PublishBuildArtifacts@1
